# install numpy library

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# Numpy Arry Operactions

# 1.Importing library

In [3]:
import numpy as np

# 2.Numpy Version Check

In [4]:
np.version.version

'1.24.4'

# 3.1 Creating 1D array 

# 1.syntax :numpy.array([Values])

# 2. Values:Elements in the array

In [5]:
first_array = np.array([1,2,3,4,5])

# 3.2 printing 1D array

In [6]:
print(first_array)

[1 2 3 4 5]


# 4.TWO DIMESIONAL ARRAY

# syntax: numpy.array([values 1],[values 2])

# 2. values: elements in the array

In [7]:
second_array = np.array([(4,5,6),(7,8,9)]) 

In [8]:
print(second_array)

[[4 5 6]
 [7 8 9]]


# 5.np.array

In [9]:
third_array = np.array([[(10,11,12),(13,14,15)],[(16,17,18),(13,14,15)]])

In [10]:
print(third_array )

[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [13 14 15]]]


# 6.zero array

In [35]:
zero_array = np.zeros((22,7))

In [36]:
print(zero_array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


# 7.Ones array

In [43]:
ones_array = np.ones((4,6))

In [44]:
print(ones_array)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


# 8.Linspace

In [70]:
spaced_num = np.linspace(0,20,10)

In [71]:
print(spaced_num)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


# creating array

In [76]:
my_array = np.array([6,7,8])

In [77]:
print(my_array)

[6 7 8]


In [78]:
arr_ones = np.ones([3,4])

In [79]:
print(arr_ones )

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [80]:
my_matrix = np.array([(11,23,45),(22,55,89)])

In [81]:
print(my_matrix)

[[11 23 45]
 [22 55 89]]


# transpose

In [85]:
matrix_transpose = np.transpose(my_matrix)

In [86]:
print(matrix_transpose)

[[11 22]
 [23 55]
 [45 89]]


In [88]:
arr_ones.ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [89]:
my_array.ravel()

array([6, 7, 8])

In [90]:
my_matrix.ravel()

array([11, 23, 45, 22, 55, 89])

In [95]:
my_array.reshape(3,1)

array([[6],
       [7],
       [8]])

In [98]:
arr_ones.reshape(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [105]:
my_matrix.reshape(3,2)

array([[11, 23],
       [45, 22],
       [55, 89]])

In [106]:
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Array with Random Number

In [114]:
np.random.random([4,4])

array([[0.13595293, 0.3146693 , 0.16360492, 0.80753811],
       [0.0254022 , 0.16855209, 0.04967567, 0.21002432],
       [0.80573411, 0.34419558, 0.49615626, 0.35026615],
       [0.61417563, 0.1545087 , 0.57604526, 0.94181686]])